- .gitignore
- README.md
- samples/docker-compose/docker-compose.yaml
- tutorials/docker-compose.md
> Add docker compose tutorial

- tutorials/cloud-foundry.md
- tutorials/kubernetes-to-kubernetes.md
- tutorials/ui-k8s-workflow.md
- tutorials/ui-local-workflow.md
- tutorials/ui-operator-workflow.md
> Add more demo flow stubs

- samples/kubernetes-to-kubernetes/api-deployment.yaml
- samples/kubernetes-to-kubernetes/api-ingress.yaml
- samples/kubernetes-to-kubernetes/api-service.yaml
- samples/kubernetes-to-kubernetes/redis-deployment.yaml
- samples/kubernetes-to-kubernetes/redis-ingress.yaml
- samples/kubernetes-to-kubernetes/redis-service.yaml
- samples/kubernetes-to-kubernetes/web-deployment.yaml
- samples/kubernetes-to-kubernetes/web-ingress.yaml
- samples/kubernetes-to-kubernetes/web-service.yaml
- tutorials/kubernetes-to-kubernetes.md
> Add support for kube2kube

- samples/cloud-foundry/5dcd16f86328acc2.yaml
- samples/cloud-foundry/main.js
- samples/cloud-foundry/manifest.yml
- samples/cloud-foundry/package-lock.json
- samples/cloud-foundry/package.json
- tutorials/cloud-foundry.md
Signed-off-by: Harikrishnan Balagopal <Harikrishnan.Balagopal@ibm.com>
> Added a sample app for demoing cloud foundry translation using 3 step process.

- .gitignore
> Added m2k_collect to git ignore

- tutorials/dockerfile-containerization.md
Signed-off-by: seshapad <seshapad@in.ibm.com>
> Added docker containerization document

- tutorials/dockerfile-containerization.md
Signed-off-by: seshapad <seshapad@in.ibm.com>
> Fixed typos and description in dockerfile-containerization document

- samples/cloud-foundry/cfapps.yaml
> Add runtime artifacts to cloud-foundry sample

- samples/cloud-foundry/cfapps.yaml
- samples/cloud-foundry/cluster.yaml
> Change group to konveyor

- samples/language-platforms/javagradle/Dockerfile
- samples/language-platforms/javagradle/m2kdfdetect.sh
Signed-off-by: Harikrishnan Balagopal <Harikrishnan.Balagopal@ibm.com>
> changed field names to follow JSON naming convention

- samples/language-platforms/golang/main.go
- samples/language-platforms/nodejs/main.js
- samples/language-platforms/php/php/index.php
- samples/language-platforms/python/main.py
- samples/language-platforms/ruby/app.rb
- samples/language-platforms/ruby/views/main.erb
Signed-off-by: Harikrishnan Balagopal <Harikrishnan.Balagopal@ibm.com>
> Change sample apps to handle requests on the correct ingress path

- samples/docker-compose/multiple-services/docker-compose.yaml
> add port to redis so that move2kube can pick up on it

- README.md
> Correct the contributions link

- samples/kubernetes-to-kubernetes/web-ingress.yaml
> update ingress from v1beta1 to v1 to avoid it trying to convert

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/workflows/assignproject.yml
> chore: Add github templates and assign project action

- .github/workflows/assignproject.yml
- .github/workflows/labelpr.yml
> feat: label pull requests based on their title

- .gitignore
- README.md
> chore: fix move2kube website url

- README.md
> chore: add instructions to bring up the UI

- samples/language-platforms/custom-java-gradle-containerizer/m2kdfdetect.sh
> fix: shebang is required to use bash shell

- samples/auth/auth.json
> feat: add a sample auth.json

- samples/language-platforms/nodejs/package.json
Signed-off-by: Akash Nayak <akash19nayak@gmail.com
```
? Select all services that are needed:
Hints:
[The services unselected here will be ignored.]
[Use arrows to move, space to select, <right> to all, <left> to none, type to filter]
> [✓]  nodewebserver
```
> fix: Change NodeJS service name

- samples/language-platforms/ruby/Gemfile
- samples/language-platforms/ruby/config.ru
- samples/language-platforms/ruby/ruby.rb
- samples/language-platforms/ruby/views/main.erb
> fix: Updated ruby sample

- samples/language-platforms/django/simplewebapp/settings.py
> fix: Fix minor bug in the django sample

- .github/workflows/release.yml
- releasenotes-config.js
> ci: make this repo part of the release workflow

- samples/language-platforms/rust/Cargo.toml
- samples/language-platforms/rust/Rocket.toml
- samples/language-platforms/rust/src/main.rs
> feat: Add Rust sample with Rocket web framework

- samples/cloud-foundry/cfapps.yaml
- samples/cloud-foundry/cluster.yaml
> fix: Update cfapps.yaml with new move2kube collect output

- samples/enterprise-app/config/m2kconfig.yaml
> feat: add config file for e2e-demo app

- samples/enterprise-app/config/m2kconfig.yaml
> fix: the config file for demo purpose

- samples/cloud-foundry/cfapps.yaml
Signed-off-by: seshapad <seshapad@in.ibm.com>
> feat: Upgrades to match m2k v3

- samples/cloud-foundry/cfapps.yaml
- samples/cloud-foundry/cluster.yaml
- samples/enterprise-app/collect/k8s/cluster.yaml
- samples/unified-flow/cfnodejs/manifest.yml
- samples/unified-flow/cfnodejs/package.json
- samples/unified-flow/m2k_collect/cfapps.yaml
- samples/unified-flow/m2k_collect/cluster.yaml
> fix: Anonymize the m2k_collect info

- README.md
> fix: fix broken tutorials link

- samples/cloud-foundry/m2k_collect/cf/cfapps.yaml
- samples/enterprise-app/collect/cf/cfapps.yaml
> fix: Update the cfapps.yaml files

- samples/enterprise-app/src/customers/pom.xml
- samples/enterprise-app/src/customers/src/main/resources/application-cloudfoundry.properties
- samples/enterprise-app/src/customers/src/main/resources/application-openshift.properties
- samples/enterprise-app/src/gateway/pom.xml
- samples/enterprise-app/src/gateway/src/main/resources/application-cloudfoundry.properties
- samples/enterprise-app/src/gateway/src/main/resources/application-local.properties
- samples/enterprise-app/src/orders/pom.xml
- samples/enterprise-app/src/orders/src/main/resources/application-cloudfoundry.properties
> fix: the enterprise app sample so docker images build correctly

- samples/enterprise-app/config/m2kconfig.yaml
> fix: the config yaml for enterprise app for v3

- samples/enterprise-app/src/gateway/manifest.yml
- samples/enterprise-app/src/orders/manifest.yml
> fix: the cloudfoundry jar filenames

- samples/enterprise-app/database/database-deployment.yaml
- samples/enterprise-app/database/database-secret.yaml
- samples/enterprise-app/database/database-service.yaml
- samples/enterprise-app/src/customers/src/main/resources/application-prod-externaldb.properties
- samples/enterprise-app/src/inventory/src/main/resources/application-prod-externaldb.properties
- samples/enterprise-app/src/orders/src/main/resources/application-prod-externaldb.properties
> chore: run all 3 databases from a single database service

- samples/enterprise-app/collect/cf/cfapps.yaml
> fix: Update the cfapps.yaml with VCAP_SERVICES in orders app

- samples/enterprise-app/config/m2k.plan
- samples/enterprise-app/config/m2kconfig.yaml
- samples/enterprise-app/config/m2kqacache.yaml
> chore: update config and add plan and qacache files

- samples/enterprise-app/src/customers/README.md
- samples/enterprise-app/src/customers/manifest.yml
- samples/enterprise-app/src/frontend/README.md
- samples/enterprise-app/src/frontend/manifest.yml
- samples/enterprise-app/src/frontend/package-lock.json
- samples/enterprise-app/src/frontend/package.json
- samples/enterprise-app/src/gateway/README.md
- samples/enterprise-app/src/gateway/manifest.yml
- samples/enterprise-app/src/inventory/README.md
- samples/enterprise-app/src/inventory/manifest.yml
- samples/enterprise-app/src/orders/README.md
> feat: Add Cloud Foundry deployment manifest files and document deployment related instructions

- samples/enterprise-app/src/customers/manifest.yml
- samples/enterprise-app/src/frontend/manifest.yml
- samples/enterprise-app/src/gateway/manifest.yml
- samples/enterprise-app/src/inventory/manifest.yml
- samples/enterprise-app/src/orders/manifest.yml
> fix: Remove random-route from the enterprise-app's CF manifest.yml files

- samples/enterprise-app/src/README.md
- samples/enterprise-app/src/deploy-to-cf.sh
- samples/enterprise-app/src/deploy-to-ibmcloud-cf.sh
- samples/enterprise-app/src/frontend/package.json
> feat: Add script to deploy to ibmcloud cf. Update the scripts and make them compatible with Linux and MacOS. Add exception handling.

- samples/enterprise-app/src/deploy-to-cf.sh
- samples/enterprise-app/src/deploy-to-ibmcloud-cf.sh
- samples/enterprise-app/src/frontend/server.js
> fix: Minor changes in server.js for CE deployment

- samples/enterprise-app/src/customers/manifest.yml
- samples/enterprise-app/src/deploy-to-cf.sh
- samples/enterprise-app/src/frontend/manifest.yml
- samples/enterprise-app/src/gateway/manifest.yml
- samples/enterprise-app/src/inventory/manifest.yml
- samples/enterprise-app/src/orders/manifest.yml
> fix: Update the CF deployment script to use original services name. Fix services starting timeout issue
